travis:
  secure:
    BINSTAR_TOKEN: KHgEChs97wEAURpdf4LiF0OrnMXW33gAQQnM+6jAWIXb5Xe0ojlStAwlgM1MK3t4/FtLA4gel6iflo8bIGQnp23vBZBfenFxAXYEJ7B/JUf7OWQpuCSPZPP+P94lTnEm9Xq0ackgdTI0i2JDNDZXO3EnVH+eYH+uCEpnngE0bh+BCnZS6s8qmFBH/Z/NsuTVWNb4cctBCJtUEVSZUBIuubwkf/2504dMQ81s5WO7U4f246RZbpjzc4sVoCGVIuYlHb4QUGmLaI/lMoSCvRduD7OpscHKRQrvfk9RswEU8kNoMvtogqN7T583sGBPEYdniZKpBc6FDTh+t9CgXv97Cb1Sf2dT0R53Gw72MCeNW27B32WcSD1Crrmr8XDi6On3WvJuSrkqqTZHqZkWXICED5UgsCYEKjZpUS/U8XzE+1W0kSs2yy+t5yTpTfKqeF7W/f3JG/eKPjM3x6zYhp1QeBZjWXdlzHIKm6HliyZhBoexq/PnNmSu30sSKYOMTdcngLY7rqOQT7sB9WWAw6CFliEWcwJghu3TfOl2PqOU/38su/9Ml7Uz8TAnc/MoMnV81kZBE+vnQRTgs1gtQ9m3xgp+k+zAnfmq80FgEK8Q2fSswj/9LV8emWWqaZByyOQZydEQ2JnjOwI8gyDO9Pe/cNMatNyJqZPm9DEq6/E+QbE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
