travis:
  secure:
    BINSTAR_TOKEN: XMRGXoZbMGddOo1bNM1SEa+AlAmBspYk73XPniFV1x7YgfNHKYPo2El9Yk/liychSiE91aCkKAAsYvqUKuiruU6yBhvDcOQkCerARZ3xMghajk+LxUSs3QQFVt5qDv+349XxxGTgpQOPzxhynrR626MLtFnrOKDEhncq0OBrcet0mBMckL2eQt7ZDlFdTUSgUPqYN5kB2b9pr3lQAyqEVYvjsS6Xt+hny95WIrFo7rvyUJ7U9b1N8MzPTd6LRhebbBWLKuy0kr8IpyD4XP2HkEOegOctHr5gN2D3Vxaq0I6QeC0BnixrO6hRMbodRRBK4+fR2tblLlnQhZwtnyaMS2j4Sp6hKryd/BYhczgOVlrqsT0tBK7V1a27k7C+Gr06mLq/GamKhPHyLrFjiIrIfGDE2eK23MCT49qSowN+uWWO8Sr/X/WpOcOZO9fBJWW9W89NhoeRfcPGNncisqOy3oGfe0Ak9xl+b3N5f9wRH+UNQ073o/yh1Orh+DW07mahgLp+bnws6ZV6mpGNLYvFSx+tQvxWzhkG18sivyef78znXvdYJdGF7nol1oszhZDsjgw2pDuhEZRZ327ly+uGDhKiK4vFXvmdkg9V6PuMSS3fQ3XgERBHjR3p7o1KQVk/B2H0vasvtplUzDKpjTHUOR2qNwu294crKsMrpWixKgo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
